let
    Source = Csv.Document(File.Contents(BaseFolder & "/FactProject.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    Nulls = Table.ReplaceValue(Headers, "", null, Replacer.ReplaceValue, Table.ColumnNames(Headers)),
    Typed = Table.TransformColumnTypes(Nulls, {
        {"project_id", type text},
        {"reporting_date", type date},
        {"lifecycle", type text},
        {"phase", type text},
        {"forecast_finish", type date},
        {"actual_finish", type date},
        {"last_reporting_date", type date},
        {"approved_budget", Int64.Type},
        {"planned_cost", Int64.Type},
        {"forecast_cost", Int64.Type},
        {"actual_cost", Int64.Type},
        {"budget_remaining", Int64.Type},
        {"actual_vs_planned", Int64.Type},
        {"actual_vs_planned_pct", type number},
        {"forecast_variance", Int64.Type},
        {"forecast_variance_pct", type number},
        {"schedule_variance_days", Int64.Type},
        {"percentage_complete", type number},
        {"overall_rag", type text},
        {"open_risks", Int64.Type},
        {"critical_risks", Int64.Type},
        {"risk_exposure", Int64.Type},
        {"open_issues", Int64.Type},
        {"critical_issues", Int64.Type},
        {"overdue_actions", Int64.Type},
        {"overdue_tasks", Int64.Type},
        {"overdue_milestones", Int64.Type},
        {"critical_milestones_overdue", Int64.Type},
        {"milestones_due", Int64.Type},
        {"dependency_exposure", Int64.Type},
        {"schedule_rag", type text},
        {"cost_rag", type text},
        {"risk_rag", type text},
        {"issues_rag", type text},
        {"milestones_rag", type text},
        {"dependencies_rag", type text},
        {"actions_rag", type text},
        {"reporting_rag", type text}
    }, "en-US")
in
    Typed
