'use strict';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const eur=n=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const compact=n=>n>=1e6?'€'+(n/1e6).toFixed(2)+'m':eur(n);
const views=['Executive portfolio','Project health','Schedule & milestones','RAID & actions','Financial performance','Dependencies','Project detail'];
let meta,state,page=0,selected='P03',requestNumber=0;
const badge=(rag,lifecycle='Active')=>`<span class="badge ${lifecycle==='Active'?esc(rag):'neutral'}">${esc(lifecycle==='Active'?rag:lifecycle)}</span>`;
const link=p=>`<button class="project-link" data-project="${esc(p.project_id)}">${esc(p.project_name||p.project_id)}</button>`;
const panel=(title,body,small='')=>`<section class="panel"><div class="panel-head"><h2>${title}</h2><small>${small}</small></div>${body}</section>`;
const body=html=>`<div class="panel-body">${html}</div>`;
const card=(label,value,note='',cls='')=>`<article class="kpi ${cls}"><label>${label}</label><strong>${value}</strong><small>${note}</small></article>`;
function table(headers,rows){return rows.length?`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>'<tr>'+row.map(c=>`<td>${c}</td>`).join('')+'</tr>').join('')}</tbody></table></div>`:'<p class="empty">No records match this view.</p>';}
function chart(rows,key,label,color='#437565'){
 const width=520,height=125,max=Math.max(1,...rows.map(r=>r[key]));
 const points=rows.map((r,i)=>`${10+i*(width-20)/Math.max(1,rows.length-1)},${height-10-r[key]/max*(height-25)}`).join(' ');
 return `<svg class="chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc(label)}"><title>${esc(label)}: ${rows.map(r=>esc(r[key])).join(', ')}</title>${[25,65,105].map(y=>`<line x1="10" y1="${y}" x2="510" y2="${y}" stroke="#e5eae4"/>`).join('')}<polyline points="${points}" fill="none" stroke="${color}" stroke-width="3"/>${rows.map((r,i)=>`<circle cx="${10+i*(width-20)/Math.max(1,rows.length-1)}" cy="${height-10-r[key]/max*(height-25)}" r="3" fill="${color}"/>`).join('')}</svg><div class="chart-labels"><span>${esc(rows[0]?.reporting_date||'')}</span><span>${esc(label)} · scale 0–${max.toFixed(0)}</span><span>${esc(rows.at(-1)?.reporting_date||'')}</span></div>`;
}
function projectTable(rows){return table(['Project / accountable owner','Department','Health','Completion','Forecast variance','Key exception'],rows.map(p=>[`${link(p)}<small>${esc(p.project_id)} · ${esc(p.manager)}</small>`,esc(p.department),badge(p.overall_rag,p.lifecycle),`${p.percentage_complete}%<div class="progress"><span style="width:${p.percentage_complete}%"></span></div>`,`${eur(p.forecast_variance)}<small>${p.forecast_variance_pct}% vs approved</small>`,esc(p.health_drivers[0]?.reason||'Within configured tolerances')]));}
function milestoneTable(rows){return table(['Project','Milestone','Baseline','Forecast / actual','Variance','Status'],rows.map(m=>[link({project_id:m.project_id}),`${esc(m.milestone_name)}<small>${esc(m.criticality)}</small>`,m.baseline_date,`${m.forecast_date}<small>${m.actual_date?'Actual '+m.actual_date:'Open milestone'}</small>`,`${m.days_variance} days`,badge(m.critical_overdue?'Red':m.overdue?'Amber':'Green')+' '+esc(m.status)]));}
function actionTable(rows){return table(['Project','Action','Owner','Due date','State'],rows.map(a=>[link({project_id:a.project_id}),esc(a.title),esc(a.owner),a.due_date,badge(a.overdue?'Red':'Green')+' '+esc(a.status)]));}
function executive(){const k=state.kpis;
 const active=state.projects.filter(p=>p.lifecycle==='Active');
 return `<div class="kpis">${card('Active projects',k.active_projects,`${k.completed_projects} completed · ${k.on_hold_projects} on hold`)}${card('Require intervention',k.red,`${k.amber} additional projects at risk`,'critical')}${card('Approved portfolio budget',compact(k.approved_budget),'Active projects · simulated EUR')}${card('Forecast variance',compact(k.forecast_variance),`${k.forecast_variance_pct}% vs approved budget`)}</div>
 <div class="grid">${panel('Portfolio health · weekly history',body(chart(state.history,'red','Active Red projects','#b85a50')), 'Active scope at each period')}${panel('Delivery confidence',body(`<div class="legend"><span>● Green ${k.green}</span><span>● Amber ${k.amber}</span><span>● Red ${k.red}</span></div><div class="status-bar">${[['green','#5d8a70'],['amber','#d0a259'],['red','#b85a50']].map(([key,c])=>`<span style="background:${c};width:${100*k[key]/Math.max(1,k.active_projects)}%"></span>`).join('')}</div><div class="stat-row"><span>Critical milestones overdue</span><b>${k.critical_milestones_overdue}</b></div><div class="stat-row"><span>Exposed dependencies</span><b>${k.dependency_exposure}</b></div><div class="stat-row"><span>Overdue actions</span><b>${k.overdue_actions}</b></div><div class="note">RAG reflects the most severe governance dimension. Click a project to inspect its evidence.</div>`))}</div>
 ${panel('Projects requiring attention',projectTable(active.filter(p=>p.overall_rag!=='Green')), 'Sorted by severity')}
 <div class="grid">${panel('Shared resource constraints',body(state.resource_capacity.filter(r=>r.overload_hours>0).map(r=>`<div class="stat-row"><span>${esc(r.resource_name)}</span><b>${r.allocated_hours}h / ${r.capacity_hours}h</b></div>`).join('')||'<p>No overloaded resources.</p>'),'Full-portfolio workload')}${panel('Management focus',body(`<p>${k.red} active projects need sponsor review. Confirm owners and due dates for recovery, funding and dependency decisions.</p><div class="note">Download the weekly report for named exceptions and rule-derived decisions from this exact reporting period.</div>`))}</div>`;
}
function health(){let rows=[];for(const dep of meta.departments){const p=state.projects.filter(p=>p.department_id===dep.department_id&&p.lifecycle==='Active');if(p.length)rows.push([esc(dep.department_name),p.length,...['Green','Amber','Red'].map(r=>p.filter(x=>x.overall_rag===r).length)]);}
 return `<div class="grid">${panel('Active health by department',table(['Department','Active','Green','Amber','Red'],rows))}${panel('Why projects need attention',body(['schedule','cost','risk','issues','milestones','dependencies','actions','reporting'].map(dim=>{const n=state.projects.filter(p=>p.lifecycle==='Active'&&p.health_dimensions[dim]!=='Green').length;return `<div class="bar-row"><span>${dim}</span><div class="bar"><span style="width:${100*n/Math.max(1,state.kpis.active_projects)}%"></span></div><b>${n} projects</b></div>`;}).join('')))}</div>${panel('Project register',projectTable(state.projects))}${rulesForm()}`;
}
function schedule(){const k=state.kpis;return `<div class="kpis">${card('Milestones due',k.milestones_due,'Next 14 days · Active projects')}${card('Overdue milestones',k.overdue_milestones,'Open and past baseline')}${card('Critical gates overdue',k.critical_milestones_overdue,'Immediate PMO attention','critical')}${card('Average finish variance',k.average_schedule_variance+'d','Unweighted Active-project average')}</div>${panel('Milestone register',milestoneTable([...state.milestones].sort((a,b)=>b.critical_overdue-a.critical_overdue||b.days_variance-a.days_variance)),'Includes completed, held and active projects in current filter')}`;}
function raid(){const k=state.kpis;return `<div class="kpis">${card('Open risks',k.open_risks,`${k.critical_risks} critical exposures`)}${card('Open issues',k.open_issues,`${k.critical_issues} critical issues`)}${card('Overdue actions',k.overdue_actions,'Across Active projects')}${card('Risk scoring','1–25','Ordinal probability × impact')}</div>${panel('Risk register',table(['Project','Risk / mitigation','P × I','Exposure','Owner / due','Age / escalation','Status'],state.risks.map(r=>[link({project_id:r.project_id}),`${esc(r.title)}<small>${esc(r.mitigation)}</small>`,`${r.probability} × ${r.impact}`,r.exposure,`${esc(r.owner)}<small>${r.due_date}</small>`,`${r.age_days}d · ${esc(r.escalation_status)}`,esc(r.status)])))}${panel('Issue register',table(['Project','Issue','Severity','Owner','Age','State'],state.issues.map(i=>[link({project_id:i.project_id}),esc(i.title),esc(i.severity),esc(i.owner),i.age_days+'d',esc(i.status)])))}${panel('Action register',actionTable(state.actions))}${panel('Assumption review',table(['Project','Assumption','Review due','State'],state.assumptions.map(a=>[link({project_id:a.project_id}),esc(a.statement),a.review_date,esc(a.status)])))}`;}
function finance(){const k=state.kpis;const active=state.projects.filter(p=>p.lifecycle==='Active');const max=Math.max(1,...active.map(p=>p.forecast_cost));return `<div class="kpis">${card('Approved budget',compact(k.approved_budget),'Active projects')}${card('Actual spend',compact(k.actual_cost),'Cumulative cost transactions')}${card('Forecast at completion',compact(k.forecast_cost),'Current reporting assumptions')}${card('Forecast over budget',k.projects_over_budget,'Projects above approved budget')}</div><div class="grid">${panel('Budget vs forecast',body(active.map(p=>`<div class="bar-row"><span>${link(p)}</span><div><div class="financial-bar" style="width:${100*p.approved_budget/max}%;background:#b2c6b5"></div><div class="financial-bar" style="width:${100*p.forecast_cost/max}%;background:${p.forecast_variance_pct>=state.rules.cost_red_pct?'#b85a50':'#406d5c'}"></div></div><span>${compact(p.forecast_cost)}</span></div>`).join('')), 'Light: approved · dark: forecast')}${panel('Portfolio forecast movement',body(chart(state.history,'forecast_cost','Simulated EUR')+`<div class="note">The historical Active-project population changes when projects complete or go on hold. Use Project Detail for like-for-like cost movement.</div>`))}</div>${panel('Financial control register',table(['Project','Budget','Planned to date','Actual','Forecast','Actual − plan','Forecast − budget','Cost status'],state.projects.map(p=>[link(p),eur(p.approved_budget),eur(p.planned_cost),eur(p.actual_cost),eur(p.forecast_cost),eur(p.actual_vs_planned),`${eur(p.forecast_variance)} (${p.forecast_variance_pct}%)`,badge(p.health_dimensions.cost)])))}`;}
function edgeRows(rows){return rows.map(d=>`<div class="edge"><div class="edge-node">${link({project_id:d.upstream_project_id,project_name:d.upstream_project})}<small>${esc(d.upstream_milestone_id)} · available ${d.available_date}</small></div><div class="edge-middle">${badge(d.severe?'Red':d.exposure_days?'Amber':'Green')}<div class="edge-arrow"></div>${d.exposure_days} days exposure</div><div class="edge-node">${link({project_id:d.project_id,project_name:d.downstream_project})}<small>${esc(d.downstream_task_id)} · needed ${d.needed_date}</small></div></div>`).join('')||'<p class="empty">No dependency edges in this scope.</p>';}
function dependencies(){return `<div class="alert">Exposure = upstream availability + lag − downstream planned start, floored at zero. This is direct interface exposure, not an automatic critical-path reschedule.</div>${panel('Cross-project dependency map',edgeRows(state.dependencies),'Project filters apply to the receiving project')}${panel('Dependency controls',table(['Edge','Upstream gate','Downstream task','Criticality','Exposure','Required action'],state.dependencies.map(d=>[d.dependency_id,d.upstream_milestone_id,d.downstream_task_id,d.criticality,d.exposure_days+' days',esc(d.required_action)])))}`;}
function rulesForm(){return panel('Configurable governance thresholds',body(`<details><summary>Review / change scenario rules</summary><form id="rules-form" class="form-grid">${Object.entries(state.rules).map(([k,v])=>`<label>${esc(k.replaceAll('_',' '))}<input name="${esc(k)}" type="number" min="1" step="1" value="${v}" required></label>`).join('')}<button class="button dark" type="submit">Save scenario thresholds</button></form></details><p>Threshold changes recalculate all 12 periods in the scenario. Baseline source files stay unchanged.</p>`));}
const editDefs={budgets:['project_id',['forecast_cost']],statuses:['project_id',['forecast_finish']],milestones:['milestone_id',['forecast_date']],risks:['risk_id',['probability','impact','status','mitigation_status']],issues:['issue_id',['status','resolution_date']],actions:['action_id',['status']],allocations:['allocation_id',['allocated_hours']]};
function detail(){let p=state.projects.find(p=>p.project_id===selected)||state.projects[0];if(!p)return '<p class="empty">No project matches the filters.</p>';selected=p.project_id;
 const rows=k=>state[k].filter(r=>r.project_id===selected);
 return `<label for="project-select">Project drill-through</label><br><select id="project-select" class="detail-select">${state.projects.map(x=>`<option value="${x.project_id}" ${x.project_id===selected?'selected':''}>${esc(x.project_name)}</option>`).join('')}</select><div class="kpis">${card('Overall health',badge(p.overall_rag,p.lifecycle),esc(p.manager))}${card('Complete',p.percentage_complete+'%','Unweighted completed task count')}${card('Forecast variance',eur(p.forecast_variance),p.forecast_variance_pct+'% vs approved')}${card('Finish variance',p.schedule_variance_days+'d','Compared with approved planned finish')}</div><div class="grid">${panel('Health drivers & accountability',body(`<p>${esc(p.story)}</p><div class="stat-row"><span>Sponsor</span><b>${esc(p.sponsor)}</b></div>${p.health_drivers.map(d=>`<div class="driver">${badge(d.rag)}<div><b>${esc(d.dimension)}</b><br>${esc(d.reason)}</div></div>`).join('')||'<p>All dimensions are within tolerance.</p>'}`))}${panel('Saved scenario controls',body(`<p>Change synthetic inputs and observe recalculated exposure. Edits are reversible and isolated from the baseline.</p><form id="edit-form" class="form-grid"><label>Record type<select id="edit-table">${Object.keys(editDefs).map(k=>`<option>${k}</option>`).join('')}</select></label><label>Record<select id="edit-record"></select></label><label>Field<select id="edit-field"></select></label><label>New value<span id="edit-value-wrap"></span></label><button class="button dark" type="submit">Save scenario</button></form><button id="reset" class="button danger" style="margin-top:12px">Reset all scenario edits</button><p class="audit">Baseline is immutable. Reset affects scenario edits and rules only; audit history remains.</p>`))}</div>${panel('Milestone evidence',milestoneTable(rows('milestones')))}<div class="grid">${panel('Forecast cost history',body(chart(state.project_history[selected],'forecast_cost','Simulated EUR')))}${panel('Project health history',table(['Period','RAG','Complete','Risk exposure','Finish variance'],state.project_history[selected].map(h=>[h.reporting_date,badge(h.overall_rag),h.percentage_complete+'%',h.risk_exposure,h.schedule_variance_days+'d'])))}</div>${panel('Incoming dependency exposure',edgeRows(rows('dependencies')))}${panel('Outgoing dependency commitments',edgeRows(state.dependencies.filter(d=>d.upstream_project_id===selected)))}${panel('Project actions',actionTable(rows('actions')))}${panel('Project RAID',table(['Type','Item','State','Owner'],[...rows('risks').map(r=>['Risk',esc(r.title),`${r.status} · exposure ${r.exposure}/25`,esc(r.owner)]),...rows('issues').map(r=>['Issue',esc(r.title),`${r.status} · ${r.severity}`,esc(r.owner)])]))}${rulesForm()}${panel('Scenario audit',body('<button id="show-audit" class="button">Show recent changes</button><div id="audit"></div>'))}`;
}
function message(text,error=false){$('#message').textContent=text;$('#message').className=error?'error':'';}
async function api(path,body){const options=body?{method:'POST',headers:{'Content-Type':'application/json','X-PMO-Token':meta.token},body:JSON.stringify(body)}:{};const response=await fetch(path,options);if(!response.ok){const e=await response.json();throw Error(e.error||'Request failed');}return response.json();}
function query(){return new URLSearchParams({period:$('#period').value,department:$('#department').value,rag:$('#rag').value});}
async function refresh(){const request=++requestNumber;try{const next=await api('/api/portfolio?'+query());if(request!==requestNumber)return;state=next;render();}catch(e){message(e.message,true);}}
function render(){state.projects.sort((a,b)=>({Red:0,Amber:1,Green:2}[a.overall_rag]-{Red:0,Amber:1,Green:2}[b.overall_rag])||a.project_id.localeCompare(b.project_id));$('#title').textContent=views[page];$('#crumb').textContent=views[page];$('#asof').textContent=state.kpis.reporting_date;$('#mode').textContent=state.scenario?'SAVED SCENARIO':'BASELINE';$('#mode').className='mode'+(state.scenario?' scenario':'');$('#report').href='/api/report?'+query();$('#nav').innerHTML=views.map((v,i)=>`<button data-page="${i}" class="${i===page?'active':''}" ${i===page?'aria-current="page"':''}><span>0${i+1}</span>${v}</button>`).join('');$('#content').innerHTML=[executive,health,schedule,raid,finance,dependencies,detail][page]();bindContent();}
function recordRows(table){const p=state.projects.find(p=>p.project_id===selected);if(table==='budgets'||table==='statuses')return [p];return state[table].filter(r=>r.project_id===selected);}
function updateEditRecords(){const tableName=$('#edit-table').value;const [id,fields]=editDefs[tableName];$('#edit-record').innerHTML=recordRows(tableName).map(r=>`<option value="${esc(r[id])}">${esc(r[id])}</option>`).join('');$('#edit-field').innerHTML=fields.map(f=>`<option>${f}</option>`).join('');updateEditValue();}
function updateEditValue(){const t=$('#edit-table').value,f=$('#edit-field').value;const r=recordRows(t).find(r=>r[editDefs[t][0]]===$('#edit-record').value);let options=null;if(f==='status')options=t==='risks'?['Open','Closed']:t==='issues'?['Open','Resolved']:['Open','Done'];if(f==='mitigation_status')options=['Not started','In progress','Complete'];const v=r?.[f]??'';$('#edit-value-wrap').innerHTML=options?`<select id="edit-value" aria-label="New value">${options.map(o=>`<option ${o===v?'selected':''}>${o}</option>`).join('')}</select>`:`<input id="edit-value" aria-label="New value" type="${['forecast_cost','probability','impact','allocated_hours'].includes(f)?'number':'date'}" value="${esc(v)}" required>`;}
function bindContent(){document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>{selected=b.dataset.project;page=6;if(!state.projects.some(p=>p.project_id===selected)){$('#department').value='';$('#rag').value='';refresh();}else render();});if($('#project-select'))$('#project-select').onchange=e=>{selected=e.target.value;render();};if($('#edit-form')){updateEditRecords();$('#edit-table').onchange=updateEditRecords;$('#edit-record').onchange=updateEditValue;$('#edit-field').onchange=updateEditValue;$('#edit-form').onsubmit=async e=>{e.preventDefault();const t=$('#edit-table').value,f=$('#edit-field').value;let v=$('#edit-value').value;if(['forecast_cost','probability','impact','allocated_hours'].includes(f))v=Number(v);const updates={[f]:v};if(t==='issues'&&f==='status')updates.resolution_date=v==='Resolved'?state.kpis.reporting_date:'';try{await api('/api/change',{operation:'edit',revision:state.revision,table:t,row_id:$('#edit-record').value,reporting_date:state.kpis.reporting_date,updates});await refresh();message('Scenario saved. Project health, dependencies and reporting have been recalculated.');}catch(err){message(err.message,true);}};$('#reset').onclick=async()=>{try{await api('/api/change',{operation:'reset',revision:state.revision});await refresh();message('Baseline restored. Audit history retained.');}catch(e){message(e.message,true);}};$('#show-audit').onclick=async()=>{try{const rows=await api('/api/audit');$('#audit').innerHTML=table(['When','Operation','Change'],rows.map(r=>{const p=JSON.parse(r.payload);return [esc(r.at),esc(r.operation),esc(p.table?`${p.table} / ${p.row_id}: ${JSON.stringify(p.updates)}`:r.operation)];}));}catch(e){message(e.message,true);}};}
 if($('#rules-form'))$('#rules-form').onsubmit=async e=>{e.preventDefault();const rules=Object.fromEntries([...new FormData(e.target)].map(([k,v])=>[k,Number(v)]));try{await api('/api/change',{operation:'rules',revision:state.revision,rules});await refresh();message('Scenario thresholds saved and all reporting periods recalculated.');}catch(e){message(e.message,true);}};
}
$('#nav').onclick=e=>{const b=e.target.closest('[data-page]');if(b){page=Number(b.dataset.page);message('');render();}};
['period','department','rag'].forEach(id=>$('#'+id).onchange=()=>{message('');refresh();});
$('#export').onclick=async()=>{try{const result=await api('/api/export',{});message(`Exported ${result.tables} tables to the repository's output folder. Scenario mode is recorded in export-info.json.`);}catch(e){message(e.message,true);}};
(async()=>{try{meta=await api('/api/meta');$('#period').innerHTML=meta.periods.map(p=>`<option value="${p.reporting_date}">${p.reporting_date} · ${p.period_label}</option>`).join('');$('#period').value=meta.periods.at(-1).reporting_date;$('#department').innerHTML+='<option disabled>────────</option>'+meta.departments.map(d=>`<option value="${d.department_id}">${esc(d.department_name)}</option>`).join('');await refresh();}catch(e){message(e.message,true);}})();
